name: Build Raspberry Pi Image

on:
  push:
    branches: ["**"]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build-rasp1-image:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build SD image
        run: |
          nix build .#nixosConfigurations.rasp1.config.system.build.sdImage

          img=$(ls result/sd-image/*.img.zst)
          # Export for other steps
          echo "IMG_LOCATION=$img" >> $GITHUB_ENV
          echo "Built $img"
          ls -alh "$img"
      - name: Encrypt for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.RASP1_IMAGE_AGE_KEY_BASE64 }}" | base64 -d > key.txt
          age_filename=$(basename "$IMG_LOCATION").age
          echo "IMG_AGE_LOCATION=$age_filename" >> $GITHUB_ENV

          echo "Writing encrypted image file to $age_filename"
          nix run -I nixpkgs=channel:nixpkgs nixpkgs#age -- -e -i key.txt -o "$age_filename" "$IMG_LOCATION"
          ls -alh "$age_filename"
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.IMG_AGE_LOCATION }}