name: Build Raspberry Pi Image

on:
  push:
    branches: ["**"]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build-rasp1-image:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build SD image
        run: |
          nix build .#nixosConfigurations.rasp1.config.system.build.sdImage
          tree result/
      - name: Decompress image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          img=$(ls result/sd-image/*.img.zst)
          mv $img rasp1.img.zst
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: rasp1.img